services:
  web:
    build: ./smart_cradle_server
    image: smart-cradle-server:latest
    ports:
      - "80:80"
    # 개발 환경에서는 .env.example을 복사해 .env를 만들어 사용하세요
    env_file:
      - ./.env
      - ./smart_cradle_server/.env.example
    depends_on:
      - db
      - mosquitto
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./smart_cradle_server/mos.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  backup:
    image: mysql:8.0
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./backups:/backups
      - ./scripts/backup_loop.sh:/backups/backup_loop.sh:ro
    # run our backup loop script copied into the image via bind mount
    # invoke bash with the script path to avoid shebang execution permission issues
    command: ["/bin/bash","/backups/backup_loop.sh"]
    restart: unless-stopped

volumes:
  db_data: