services:
  web:
    image: joohyun7818/smart-cradle-server:latest
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - mosquitto
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mos.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

volumes:
  db_data: