services:
  web:
    image: joohyun7818/smart-cradle-flask:latest
    # Flask app listens on 80 inside container (gunicorn) -> map directly
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - mosquitto
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./smart_cradle_server/mos.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

volumes:
  db_data: